### ISSUE TITLE
Add b43-firmware to sys-firmware

### ISSUE THREAD

**Issue by k2662** [Alex313031/ThoriumOS#56]
All you would need to do is clone gentoo like:

```bash
git clone --depth=1 https://anongit.gentoo.org/git/repo/gentoo.git
```
and copy gentoo/sys-firmware/b43-firmware to ThoriumOS/sys-firmware like this:
```bash
cp -r gentoo/sys-firmware/b43-firmware ThoriumOS/sys-firmware
```

**Comment by Alex313031** [comment]
@k2662 OK good idea. Will add for ThOS V120!

**Comment by k2662** [comment]
> @k2662 OK good idea. Will add for ThOS V120!
thanks! Sorry for the late response.

**Comment by Alex313031** [comment]
@k2662 Added > https://github.com/Alex313031/ThoriumOS/commit/fb668d9cdea9aac66f3f25120a071dad65c176b8
