### ISSUE TITLE
Where do I donate

### ISSUE THREAD

**Issue by slendermon** [Alex313031/ThoriumOS#57]
Not an issue, but I want to donate for thoriumos project

**Comment by Alex313031** [comment]
@slendermon Aww thanks man. I need to add a FUNDING.yml file to this repo like I do for all the other Thorium repos.

You can donate at my paypal > https://paypal.me/alex313031?country.x=US&locale.x=en_US

**Comment by Alex313031** [comment]
@slendermon UPDATE: I added the funding file, so you should now see the normal heart shaped "sponsor" button at the top.

**Comment by slendermon** [comment]
I was on mobile and couldnt find it but now I see thank you
