### ISSUE TITLE
Cannot Install/Use Thorium

### ISSUE THREAD

**Issue by paulindr** [Alex313031/ThoriumOS#88]
I've been using Thorium for many months and had no problems until recently. I'll describe today's problem but exactly the same happened 6 days ago.

Today: I was browsing with Thorium when Avast notified me of reputed malware. Then Thorium closed and it appears that the .exe and browser icon were both deleted. The reputed malware's information is:
Name: Win32:Malware-gen
Original Location: C:\Users\hp personal\AppData\Local\Thorium\Application\Thorium.exe

Since then, I cannot successfully download or install Thorium. I did go to https://thorium.rocks/new/ and click "Install". Many Thorium files were installed but no application file [Thorium.exe] or Thorium icon was included.

As I said, the same ting happened 6 days ago. the only difference is that, the first time, I simply reinstalled Thorium without any difficulty. 

I have seen  at least one comment that Thorium is itself a virus, reputedly because it installs potentially malicious extensions. No idea if this is an accepted issue among experts.

I have no idea how to resolve the inability to reinstall Thorium lor if it's advisable to abandon the browser altogether.  Guidance would be much appreciated.

**Comment by paulindr** [comment]
Mysteriously, an icon has appeared. I can't explain why it took so long --- even a system search failed to locate it until now.
Thorium now loads. 
SO this is probably unresolvable as all that is left is why Thorium crashes with a malware warning..
I have sent the files for analysis by Avast but will now close the Help request.

**Comment by paulindr** [comment]
As above

**Comment by Alex313031** [comment]
@paulindr Thorium isn't a virus. It installs ublock origin dev build by default.

It used to install the "Google Hangouts" extension by default, and people complained about privacy, so I removed that a couple versions ago.

I have seen the installer flagged as a virus, but the actual thorium.exe executable once it is installed should never come up as a virus, unless it's something i haven't seen before

**Comment by paulindr** [comment]
Thanks Alex313031.
I was shocked to see Thorium described as a virus --- not very believable. SO it's good to see the reply.
Avast is quite happy that ,y system is clean even with Thorium now reinstalled.
If it crashes again, I'll try to get more info if I can find any.
